include:
  - docker-compose.deps.yml
services:
  webauthn-server:
    build: .
    ports:
      - "${MPO_AUTHN_APP_PORT}:8080"
    environment:
      - MPO_AUTHN_DB_HOST=${MPO_AUTHN_DB_HOST}
      - MPO_AUTHN_DB_PORT=${MPO_AUTHN_DB_PORT}
      - MPO_AUTHN_DB_NAME=${MPO_AUTHN_DB_NAME}
      - MPO_AUTHN_DB_USERNAME=${MPO_AUTHN_DB_USERNAME}
      - MPO_AUTHN_DB_PASSWORD=${MPO_AUTHN_DB_PASSWORD}
      - MPO_AUTHN_REDIS_HOST=${MPO_AUTHN_REDIS_HOST}
      - MPO_AUTHN_REDIS_PORT=${MPO_AUTHN_REDIS_PORT}
      - MPO_AUTHN_REDIS_PASSWORD=${MPO_AUTHN_REDIS_PASSWORD}
      - MPO_AUTHN_APP_RELYING_PARTY_ID=${MPO_AUTHN_APP_RELYING_PARTY_ID}
      - MPO_AUTHN_APP_RELYING_PARTY_NAME=${MPO_AUTHN_APP_RELYING_PARTY_NAME}
      - MPO_AUTHN_OPEN_TELEMETRY_SERVICE_NAME=${MPO_AUTHN_OPEN_TELEMETRY_SERVICE_NAME}
      - MPO_AUTHN_OPEN_TELEMETRY_JAEGER_ENDPOINT=${MPO_AUTHN_OPEN_TELEMETRY_JAEGER_ENDPOINT}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      jaeger:
        condition: service_healthy
    restart: unless-stopped
    # Health check removed - distroless image doesn't have curl
    # External health checking handled by start-full.sh script
