services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${MPO_AUTHN_DB_NAME}
      POSTGRES_USER: ${MPO_AUTHN_DB_USERNAME}
      POSTGRES_PASSWORD: ${MPO_AUTHN_DB_PASSWORD}
    ports:
      - "${MPO_AUTHN_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${MPO_AUTHN_DB_USERNAME} -d ${MPO_AUTHN_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "${MPO_AUTHN_REDIS_PORT}:6379"
    command: redis-server --requirepass ${MPO_AUTHN_REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: mpo-authn-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC endpoint
      - "14268:14268"  # HTTP endpoint for spans
      - "9411:9411"    # Zipkin compatible endpoint
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:16686/" ]
      interval: 10s
      timeout: 3s
      retries: 5

  webauthn-server:
    build: .
    ports:
      - "${MPO_AUTHN_APP_PORT}:8080"
    environment:
      - MPO_AUTHN_DB_HOST=${MPO_AUTHN_DB_HOST}
      - MPO_AUTHN_DB_PORT=${MPO_AUTHN_DB_PORT}
      - MPO_AUTHN_DB_NAME=${MPO_AUTHN_DB_NAME}
      - MPO_AUTHN_DB_USERNAME=${MPO_AUTHN_DB_USERNAME}
      - MPO_AUTHN_DB_PASSWORD=${MPO_AUTHN_DB_PASSWORD}
      - MPO_AUTHN_REDIS_HOST=${MPO_AUTHN_REDIS_HOST}
      - MPO_AUTHN_REDIS_PORT=${MPO_AUTHN_REDIS_PORT}
      - MPO_AUTHN_REDIS_PASSWORD=${MPO_AUTHN_REDIS_PASSWORD}
      - MPO_AUTHN_APP_RELYING_PARTY_ID=${MPO_AUTHN_APP_RELYING_PARTY_ID}
      - MPO_AUTHN_APP_RELYING_PARTY_NAME=${MPO_AUTHN_APP_RELYING_PARTY_NAME}
      - MPO_AUTHN_OPEN_TELEMETRY_SERVICE_NAME=${MPO_AUTHN_OPEN_TELEMETRY_SERVICE_NAME}
      - MPO_AUTHN_OPEN_TELEMETRY_JAEGER_ENDPOINT=${MPO_AUTHN_OPEN_TELEMETRY_JAEGER_ENDPOINT}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  redis_data:
