version: '3.8'

services:
  webauthn-test-credentials-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - webauthn-test-network

networks:
  webauthn-test-network:
    driver: bridge