name: 'Run JS E2E Tests'
description: 'Runs JavaScript E2E tests using Playwright'
runs:
  using: "composite"
  steps:
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: test-client/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('test-client/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      working-directory: test-client
      shell: bash
      run: npm ci

    - name: Install Playwright Browsers
      working-directory: test-client
      shell: bash
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      working-directory: test-client
      shell: bash
      run: npm run test:e2e

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: |
          test-client/playwright-report/
        retention-days: 7