name: 'Run JS E2E Tests'
description: 'Runs JavaScript E2E tests using Playwright'
runs:
  using: "composite"
  steps:
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: test-client/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('test-client/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      working-directory: test-client
      shell: bash
      run: npm ci

    - name: Install Playwright Browsers
      working-directory: test-client
      shell: bash
      run: npx playwright install --with-deps

    - name: Set up Docker Compose
      shell: bash
      run: |
        # Docker is pre-installed on GitHub runners, but we need docker-compose
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Run Playwright tests
      working-directory: test-client
      shell: bash
      run: |
        echo "Running Playwright tests..."
        npm run test:with-server

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: |
          test-client/playwright-report/
          test-client/test-results/
        retention-days: 7

    - name: Upload Docker Logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: docker-logs
        path: |
          docker-compose-logs.txt
        retention-days: 3
