# AI Security Analysis Configuration - Minimal Required Values Only
#
# All other values use code defaults:
# - HuggingFace upload: enabled by default (can be disabled via CLI)
# - Training parameters: optimized defaults for security analysis
# - MLX settings: optimized for Apple Silicon

# External model directories (shareable across projects)
base_models_dir: "~/shared-olmo-models/base"
fine_tuned_models_dir: "~/shared-olmo-models/fine-tuned"

# Default model optimized for Apple Silicon with MLX
default_base_model: "OLMo-2-1B-mlx-q4"

# Fine-tuning configuration - only required values
fine_tuning:
  workspace_dir: "security-ai-analysis/fine-tuning"
  default_output_name: "webauthn-security-v1"

  # Test-specific training settings for ultra-fast execution (~1 minute)
  test_training:
    max_epochs: 1          # Single epoch instead of default 3
    save_steps: 3          # Ultra-minimal: 3 saves for 30 iterations (3×10)
    eval_steps: 2          # Ultra-minimal: evaluate every 2 steps
    learning_rate: 2e-4    # Higher LR for very fast convergence
