# AI Security Analysis Configuration - Minimal Required Values Only
# 
# All other values use code defaults:
# - HuggingFace upload: enabled by default (can be disabled via CLI)
# - Training parameters: optimized defaults for security analysis
# - MLX settings: optimized for Apple Silicon

# External model directories (shareable across projects)
base_models_dir: "~/shared-olmo-models/base"
fine_tuned_models_dir: "~/shared-olmo-models/fine-tuned"

# Default model optimized for Apple Silicon with MLX
default_base_model: "OLMo-2-1B-mlx-q4"

# Fine-tuning configuration - only required values
fine_tuning:
  workspace_dir: "security-ai-analysis/fine-tuning"
  default_output_name: "webauthn-security-v1"