# Central Publishing Configuration
# Single source of truth for all client library publishing settings

# Package Configuration
packages:
  android:
    groupId: "io.github.hitoshura25"
    baseArtifactId: "mpo-webauthn-android-client"
  typescript:
    scope:
      staging: "@hitoshura25"
      production: "@vmenon25"
    basePackageName: "mpo-webauthn-client"

# Docker Configuration
docker:
  registry:
    url: "ghcr.io"
    # Credentials: Uses github.actor and GITHUB_TOKEN (hardcoded in workflows for simplicity)
  images:
    webauthn-server:
      name: "hitoshura25/webauthn-server"
      dockerhub: "hitoshura25/webauthn-server"
      description: "WebAuthn authentication server built with Ktor and Yubico java-webauthn-server"
      dockerfile: "./webauthn-server/Dockerfile"
      readme: "./webauthn-server/README.md"
    test-credentials-service:
      name: "hitoshura25/webauthn-test-credentials-service" 
      dockerhub: "hitoshura25/webauthn-test-credentials-service"
      description: "WebAuthn test credentials service for cross-platform testing with FIDO2/WebAuthn"
      dockerfile: "./webauthn-test-credentials-service/Dockerfile"
      readme: "./webauthn-test-credentials-service/README.md"

# Repository Configuration  
repositories:
  staging:
    android:
      url: "https://maven.pkg.github.com/hitoshura25/mpo-api-authn-server"
      # Credentials: Uses github.actor and GITHUB_TOKEN (hardcoded in workflow for simplicity)
    npm:
      registry: "https://npm.pkg.github.com"
      credentials:
        tokenEnv: "GITHUB_TOKEN"
  production:
    android:
      url: "https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/"
      # Credentials: Uses CENTRAL_PORTAL_USERNAME and CENTRAL_PORTAL_PASSWORD (hardcoded in workflow)
    npm:
      registry: "https://registry.npmjs.org"
      credentials:
        tokenEnv: "NPM_PUBLISH_TOKEN"

# Package Naming Templates
naming:
  staging:
    androidSuffix: "-staging"
    npmSuffix: "-staging"
  production:
    androidSuffix: ""
    npmSuffix: ""

# Metadata
metadata:
  projectUrl: "https://github.com/hitoshura25/mpo-api-authn-server"
  description: "Generated client libraries for MPO WebAuthn API - FIDO2/WebAuthn authentication"
  license: "MIT"
  author:
    name: "Hitoshura"
    email: "hitoshura25@users.noreply.github.com"
    id: "hitoshura25"

# Configuration validation
schema:
  version: "1.0"
  lastUpdated: "2025-01-16"