name: 'Docker Build and Push'
description: 'Builds docker images and publishes to Docker Hub'
inputs:
  docker_username:
    description: 'Docker username for publishing'
    required: true
  docker_password:
    description: 'Docker password for publishing'
    required: true
runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: hitoshura25/mpo-api-authn-server
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Update repo description
      uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae # v4.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: hitoshura25/mpo-api-authn-server
        short-description: ${{ github.event.repository.description }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: index.docker.io/hitoshura25/mpo-api-authn-server
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true