#!/bin/sh
set -e

# Generic entrypoint script for zero-trust services
# Auto-generated by @vmenon25/mcp-server-webauthn-client
#
# This script:
# - Sets APP_PORT with a sensible default (9001)
# - Allows override via environment variable
# - Executes the CMD specified in Dockerfile
#
# Framework-agnostic: works with FastAPI, Spring Boot, Express, etc.

# Set default port if not specified
export APP_PORT=${APP_PORT:-9001}

# Execute the CMD from Dockerfile (passed as arguments)
exec "$@"
