name: Default Branch Tests and Coverage

on:
  push:
    branches:
      - main

jobs:
  default-branch-run-tests:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-jdk
      - uses: ./.github/actions/cache-gradle
      - uses: ./.github/actions/run-tests
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  default-branch-run-js-client-e2e-tests:
    name: E2E Tests
    uses: ./.github/workflows/js-client-e2e-tests.yml
    with:
      node-version: '18'

  docker-publish:
    runs-on: ubuntu-latest
    needs: [ default-branch-run-tests, default-branch-run-js-client-e2e-tests ]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-publish
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
