name: Default Branch Tests and Coverage

on:
  push:
    branches:
      - main

jobs:
  default-branch-run-client-e2e-tests:
    name: Client E2E Tests (Web + Android)
    uses: ./.github/workflows/client-e2e-tests.yml
    with:
      node-version: '18'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      gradle_encryption_key: ${{secrets.GRADLE_ENCRYPTION_KEY }}
      docker_hub_username: ${{ secrets.DOCKER_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_PASSWORD }}
