name: Run JS Client E2E Tests

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '18'
    secrets:
      codecov_token:
        description: 'Codecov token for uploading coverage reports'
        required: true
      gradle_encryption_key:
        description: 'Gradle encryption key'
        required: true
      docker_hub_username:
        description: 'DockerHub username'
        required: true
      docker_hub_token:
        description: 'DockerHub token'
        required: true
    outputs:
      test-exit-code:
        description: 'Exit code from the tests'
        value: ${{ jobs.js-client-e2e-tests.outputs.test-exit-code }}

jobs:
  js-client-e2e-tests:
    runs-on: ubuntu-latest
    outputs:
      test-exit-code: ${{ steps.run-tests.outputs.test-exit-code }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.gradle_encryption_key }}
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Run tests and coverage
        shell: bash
        run: ./gradlew koverXmlReport --build-cache --parallel --configuration-cache

      - name: Run shadowJar for cache
        shell: bash
        run: ./gradlew shadowJar --build-cache --parallel --configuration-cache
        if: github.event_name != 'pull_request'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./build/reports/kover/report.xml
          flags: unit
          name: codecov-unit
          token: ${{ secrets.codecov_token }}
          fail_ci_if_error: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: hitoshura25/mpo-api-authn-server
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=pr

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: test-client/package-lock.json

      - name: Install test dependencies
        working-directory: test-client
        run: |
          npm ci
          # They recommend using the --with-dependencies flag however that adds additional time and tests work so far without it
          npx playwright install chromium --only-shell

      - name: Set up environment and start services
        run: |
          ./scripts/setup-secure-env.sh
          DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker compose up -d --build

          # Wait for services
          for i in {1..60}; do
            healthy_count=$(docker compose ps --format "table {{.Service}}\t{{.Status}}" | grep -c "healthy" || true)
            if [ "$healthy_count" -eq 4 ]; then
              echo "✅ All services ready"
              break
            fi
            sleep 0.5
          done

      - name: Run E2E tests
        id: run-tests
        working-directory: test-client
        run: |
          set +e
          npm test
          TEST_EXIT_CODE=$?
          set -e
          
          # Store exit code for later use
          echo "test-exit-code=$TEST_EXIT_CODE" >> $GITHUB_OUTPUT
          
          if [ $TEST_EXIT_CODE -ne 0 ]; then
            echo "❌ Tests failed with exit code $TEST_EXIT_CODE"
          else
            echo "✅ Tests passed successfully"
          fi

      - name: Stop full stack
        id: stop-full-stack
        if: always()
        run: |
          echo "Capturing Docker Compose logs..."
          docker compose logs > docker-compose-logs.txt 2>&1
          echo "Stopping Docker Compose services..."
          docker compose down -v
          echo "✅ Docker Compose services stopped"

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            test-client/playwright-report/
            test-client/test-results/
          retention-days: 3

      - name: Upload Docker Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker-logs
          path: docker-compose-logs.txt
          retention-days: 3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.docker_hub_username }}
          password: ${{ secrets.docker_hub_token }}

      - name: Build and push
        uses: docker/build-push-action@v6
        if: github.event_name != 'pull_request'
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
