name: Pull Request Tests and Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request-run-js-client-e2e-tests:
    name: Pull Request E2E Tests
    uses: ./.github/workflows/js-client-e2e-tests.yml
    with:
      node-version: '18'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      gradle_encryption_key: ${{secrets.GRADLE_ENCRYPTION_KEY}}

  pull-request-optimized-build-test:
    name: Pull Request E2E Tests (optimized?)
    uses: ./.github/workflows/optimized-build-test.yml
    with:
      node-version: '18'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      gradle_encryption_key: ${{secrets.GRADLE_ENCRYPTION_KEY}}

