name: Pull Request Tests and Coverage

on:
  pull_request:
    branches:
      - main
    paths:
      - 'webauthn-server/**'
      - 'webauthn-test-lib/**'
      # TODO: Remove the the test credential service once optimized (i.e. docker image has changed)
      - 'webauthn-test-credentials-service/**'
      - 'settings.gradle.kts'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'gradle/**'
      - '.github/workflows/pull-request.yml'
      - '.github/workflows/client-e2e-tests.yml'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  pull-request-run-client-e2e-tests:
    name: Client E2E Tests (Web + Android)
    uses: ./.github/workflows/client-e2e-tests.yml
    with:
      node-version: '18'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      gradle_encryption_key: ${{secrets.GRADLE_ENCRYPTION_KEY }}
      docker_hub_username: ${{ secrets.DOCKER_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_PASSWORD }}

