name: Cleanup PR artifacts

on:
  pull_request:
    types: [ closed ]

jobs:
  cleanup-docker-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete PR Docker images
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Cleaning up Docker images for PR #$PR_NUMBER"

          # Cleanup webauthn-server images
          gh api --paginate "/users/${{ github.repository_owner }}/packages/container/webauthn-server/versions" \
            --jq '.[] | select(.metadata.container.tags[]? | test("^pr-'$PR_NUMBER'(-|$)")) | .id' | \
          while read version_id; do
            if [ -n "$version_id" ]; then
              echo "Deleting webauthn-server version: $version_id"
              gh api -X DELETE "/users/${{ github.repository_owner }}/packages/container/webauthn-server/versions/$version_id" || echo "Failed to delete $version_id"
            fi
          done

          # Cleanup webauthn-test-credentials-service images
          gh api --paginate "/users/${{ github.repository_owner }}/packages/container/webauthn-test-credentials-service/versions" \
            --jq '.[] | select(.metadata.container.tags[]? | test("^pr-'$PR_NUMBER'(-|$)")) | .id' | \
          while read version_id; do
            if [ -n "$version_id" ]; then
              echo "Deleting test-credentials version: $version_id"
              gh api -X DELETE "/users/${{ github.repository_owner }}/packages/container/webauthn-test-credentials-service/versions/$version_id" || echo "Failed to delete $version_id"
            fi
          done

  cleanup-npm-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete PR NPM packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Cleaning up NPM packages for PR #$PR_NUMBER"

          gh api --paginate "/user/packages/npm/${{ github.repository_owner }}%2Fmpo-webauthn-client/versions" \
            --jq '.[] | select(.name | test("^pr-'$PR_NUMBER'\\.")) | .id' | \
          while read version_id; do
            if [ -n "$version_id" ]; then
              echo "Deleting NPM version: $version_id"
              gh api -X DELETE "/user/packages/npm/${{ github.repository_owner }}%2Fmpo-webauthn-client/versions/$version_id" || echo "Failed to delete $version_id"
            fi
          done

  cleanup-maven-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete PR Maven packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Cleaning up Maven packages for PR #$PR_NUMBER"

          gh api --paginate "/user/packages/maven/io.github.hitoshura25.mpo-webauthn-android-client/versions" \
            --jq '.[] | select(.name | test("^pr-'$PR_NUMBER'\\.")) | .id' | \
          while read version_id; do
            if [ -n "$version_id" ]; then
              echo "Deleting Maven version: $version_id"
              gh api -X DELETE "/user/packages/maven/io.github.hitoshura25.mpo-webauthn-android-client/versions/$version_id" || echo "Failed to delete $version_id"
            fi
          done
