name: Test WebAuthn Test Credentials Service

on:
  pull_request:
    paths:
      - 'webauthn-test-credentials-service/**'
      - 'webauthn-test-lib/**'
      - 'settings.gradle.kts'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'gradle/**'
      - '.github/workflows/test-webauthn-test-credentials-service.yml'
  push:
    branches:
      - main
    paths:
      - 'webauthn-test-credentials-service/**'
      - 'webauthn-test-lib/**'
      - 'settings.gradle.kts'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'gradle/**'
      - '.github/workflows/test-webauthn-test-credentials-service.yml'
  workflow_dispatch: # Allow manual triggering

jobs:
  test-webauthn-test-credentials-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup branch-specific Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/configuration-cache
          key: gradle-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-${{ github.ref_name }}-
            gradle-${{ runner.os }}-main-
            gradle-${{ runner.os }}-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run webauthn-test-credentials-service tests and generate coverage
        run: ./gradlew :webauthn-test-credentials-service:test :webauthn-test-credentials-service:koverXmlReport --build-cache --parallel --configuration-cache

      - name: Upload test and coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: webauthn-test-credentials-service-reports
          path: |
            webauthn-test-service/build/reports/
          retention-days: 7

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        if: github.event_name != 'pull_request'
        with:
          images: hitoshura25/webauthn-test-credentials-service
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch

      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        if: github.event_name != 'pull_request'
        with:
          context: ./webauthn-test-credentials-service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
